[build]
  publish = "frontend"
  command = "echo 'No build required for static site'"

[[redirects]]
  from = "/api/*"
  to = "https://fullstack-backend.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
