services:
  - type: web
    name: fullstack-backend
    env: python
    plan: free
    buildCommand: bash render-build.sh
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_API_KEY
        value: zuheer123
